name: coffee_start
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  bloc: ^8.1.4
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.8
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.3
  get_it: ^7.7.0
  intl: ^0.19.0
  retrofit: ^4.1.0
  flutter_cache_manager: ^3.3.2
  google_nav_bar: ^5.0.6
  persistent_bottom_nav_bar: ^6.2.1
  win32: ^5.8.0
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.1.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  retrofit_generator: ^8.1.0

flutter:
  uses-material-design: true
